name: reading_time
version: 2.0.0
authors:
  - Adib Mohsin <adibmohsin.root@gmail.com>
description: A small dart library that predicts / calculates reading time like medium does .
homepage: https://github.com/pacifio/reading_time
environment:
  sdk: ">=2.12.0<3.0.0"
dev_dependencies:
  test: ">=0.12.18"
